name = "pancakemaker-api"
main = "src/index.ts"
compatibility_date = "2025-02-01"

[vars]
ENVIRONMENT = "production"
APP_URL = "https://pancakemaker.com"

[[custom_domains]]
hostname = "api.pancakemaker.com"
override_existing_origin = true
override_existing_dns_record = true

[[d1_databases]]
binding = "DB"
database_name = "pancakemaker"
database_id = "a4da6b61-d618-4f6d-8548-07b0cab75186"
migrations_dir = "migrations"
